### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by drs143** [jennings/terraform-provider-meraki#60]
Wondering if there is a chance this project evolve further?

**Comment by jennings** [comment]
It’s not abandoned, I just don’t have a need for any more resources at my current job.

If there is any feature you want, please open an issue for it and we can discuss!

**Comment by drs143** [comment]
Hi @jennings, I appreciate your work anyway. We are using Meraki as a wireless solution, so I am personally missing everything around managing SSIDs and so on. But of course don't expect you to do Cisco's job. That's a shame on Cisco they don't provide fully equipped Meraki TF provider...

**Comment by jennings** [comment]
Based on [this documentation](https://developer.cisco.com/meraki/api-v1/), it seems like the API only would properly support an SSID data source:

```
# query one SSID
data “meraki_network_appliance_ssid” “myssid” {
  network_id = “12345”
  id = 1
}

# query all SSIDs for a network
data “meraki_network_appliance_ssids”  “all_ssids” {
  network_id = “12345”
} 
```

There’s [an API for modifying an SSID](https://developer.cisco.com/meraki/api-v1/#!update-network-appliance-ssid) , but not one for creating one, so you’d be required to import every SSID you wanted to manage with Terraform.
